#' @export
Stats <- list(
    avg.days.in.pos = Stat(
description = 'Maximum number of days in position',
name = 'avg.days.in.pos', 
in_report = TRUE),
    days.in.drawdown = Stat(
description = 'Maximum days in drawdown',
name = 'days.in.drawdown', 
in_report = TRUE),
    drawdown.money = Stat(
description = 'Maximum drawdown divided by maximum money used',
name = 'drawdown.money', 
in_report = TRUE),
    hhi.minus = Stat(
description = 'Concetration of negative trades. Inspired by the Herfindahl-Hirschman Index.',
name = 'hhi.minus', 
in_report = TRUE),
    hhi.plus = Stat(
description = 'Concetration of positive trades. Inspired by the Herfindahl-Hirschman Index.',
name = 'hhi.plus', 
in_report = TRUE),
    in.pos = Stat(
description = 'Percentage of time in position',
name = 'in.pos', 
in_report = TRUE),
    max.days.in.pos = Stat(
description = 'Maximum number of days in position',
name = 'max.days.in.pos', 
in_report = TRUE),
    max.loose = Stat(
description = 'Maximum number of loosing trades in a row',
name = 'max.loose', 
in_report = TRUE),
    max.win = Stat(
description = 'Maximum number of winning trades in a row',
name = 'max.win', 
in_report = TRUE),
    ntrades = Stat(
description = 'Total number of trades in each year',
name = 'ntrades', 
in_report = TRUE),
    profit.cost = Stat(
description = 'Total profit with costs divided by costs',
name = 'profit.cost', 
in_report = TRUE),
    return.ann = Stat(
description = 'Yearly total return divided by money of the model',
name = 'return.ann', 
in_report = TRUE),
    return.avg = Stat(
description = 'Yearly return on average capital',
name = 'return.avg', 
in_report = TRUE),
    return.pos.drawdown = Stat(
description = 'Yearly total return divided by sum of maximum drawdown and maximum used capital',
name = 'return.pos.drawdown', 
in_report = TRUE),
    sharpe = Stat(
description = 'Yearly Sharpe ratio of increments of pnl',
name = 'sharpe', 
in_report = TRUE),
    sharpe.sharpe = Stat(
description = 'Sharpe ration of yearly rolling sharpes.',
name = 'sharpe.sharpe', 
in_report = TRUE),
    sortino = Stat(
description = 'Yearly Sortino ratio of increments of pnl',
name = 'sortino', 
in_report = TRUE),
    trades.acc = Stat(
description = 'Percentage of winnig trades',
name = 'trades.acc', 
in_report = TRUE),
    trades.year = Stat(
description = 'Mean number of trades in each year',
name = 'trades.year', 
in_report = TRUE))


#' @export
acceptable_stats <- list(
    avg.days.in.pos = Stat(
description = 'Maximum number of days in position',
name = 'avg.days.in.pos', 
in_report = TRUE,
general = FALSE),
    commission = Stat(
description = 'Commissions',
name = 'commission', 
in_report = FALSE,
general = FALSE),
    days_in_trades = Stat(
description = 'Array of number of days in each trade',
name = 'days_in_trades', 
in_report = FALSE,
general = FALSE),
    days.in.drawdown = Stat(
description = 'Maximum days in drawdown',
name = 'days.in.drawdown', 
in_report = TRUE,
general = FALSE),
    drawdown.money = Stat(
description = 'Maximum drawdown divided by maximum money used',
name = 'drawdown.money', 
in_report = TRUE,
general = FALSE),
    end_inds = Stat(
description = 'Indexes of closing points',
name = 'end_inds', 
in_report = FALSE,
general = FALSE),
    hhi.minus = Stat(
description = 'Concetration of negative trades. Inspired by the Herfindahl-Hirschman Index.',
name = 'hhi.minus', 
in_report = TRUE,
general = FALSE),
    hhi.plus = Stat(
description = 'Concetration of positive trades. Inspired by the Herfindahl-Hirschman Index.',
name = 'hhi.plus', 
in_report = TRUE,
general = FALSE),
    in.pos = Stat(
description = 'Percentage of time in position',
name = 'in.pos', 
in_report = TRUE,
general = FALSE),
    max_drawdown = Stat(
description = 'Maximum drawdown',
name = 'max_drawdown', 
in_report = FALSE,
general = FALSE),
    max_used_money = Stat(
description = 'Maximum usage of capital',
name = 'max_used_money', 
in_report = FALSE,
general = FALSE),
    max.days.in.pos = Stat(
description = 'Maximum number of days in position',
name = 'max.days.in.pos', 
in_report = TRUE,
general = FALSE),
    max.loose = Stat(
description = 'Maximum number of loosing trades in a row',
name = 'max.loose', 
in_report = TRUE,
general = FALSE),
    max.win = Stat(
description = 'Maximum number of winning trades in a row',
name = 'max.win', 
in_report = TRUE,
general = FALSE),
    ntrades = Stat(
description = 'Total number of trades in each year',
name = 'ntrades', 
in_report = TRUE,
general = FALSE),
    nyears = Stat(
description = 'number of years in backtest',
name = 'nyears', 
in_report = FALSE,
general = FALSE),
    obs_per_year = Stat(
description = '',
name = 'obs_per_year', 
in_report = FALSE,
general = FALSE),
    pnl = Stat(
description = 'Profit and Loss',
name = 'pnl', 
in_report = FALSE,
general = FALSE),
    pnl_ = Stat(
description = 'Full Profit and Loss',
name = 'pnl_', 
in_report = FALSE,
general = TRUE),
    pnl_inc = Stat(
description = 'Increments of pnl',
name = 'pnl_inc', 
in_report = FALSE,
general = FALSE),
    pnl_inc_ = Stat(
description = 'Full Increments of pnl',
name = 'pnl_inc_', 
in_report = FALSE,
general = TRUE),
    pnl.mean = Stat(
description = 'Mean of increments of Profit and Loss',
name = 'pnl.mean', 
in_report = FALSE,
general = FALSE),
    profit.cost = Stat(
description = 'Total profit with costs divided by costs',
name = 'profit.cost', 
in_report = TRUE,
general = FALSE),
    report = Stat(
description = 'Backtest report',
name = 'report', 
in_report = FALSE,
general = FALSE),
    return.ann = Stat(
description = 'Yearly total return divided by money of the model',
name = 'return.ann', 
in_report = TRUE,
general = FALSE),
    return.avg = Stat(
description = 'Yearly return on average capital',
name = 'return.avg', 
in_report = TRUE,
general = FALSE),
    return.pos.drawdown = Stat(
description = 'Yearly total return divided by sum of maximum drawdown and maximum used capital',
name = 'return.pos.drawdown', 
in_report = TRUE,
general = FALSE),
    sharpe = Stat(
description = 'Yearly Sharpe ratio of increments of pnl',
name = 'sharpe', 
in_report = TRUE,
general = FALSE),
    sharpe.sharpe = Stat(
description = 'Sharpe ration of yearly rolling sharpes.',
name = 'sharpe.sharpe', 
in_report = TRUE,
general = FALSE),
    sortino = Stat(
description = 'Yearly Sortino ratio of increments of pnl',
name = 'sortino', 
in_report = TRUE,
general = FALSE),
    start_inds = Stat(
description = 'Indexes of opening points',
name = 'start_inds', 
in_report = FALSE,
general = FALSE),
    trades = Stat(
description = 'Report of trades',
name = 'trades', 
in_report = FALSE,
general = FALSE),
    trades_ = Stat(
description = 'Full Report of trades',
name = 'trades_', 
in_report = FALSE,
general = TRUE),
    trades.acc = Stat(
description = 'Percentage of winnig trades',
name = 'trades.acc', 
in_report = TRUE,
general = FALSE),
    trades.year = Stat(
description = 'Mean number of trades in each year',
name = 'trades.year', 
in_report = TRUE,
general = FALSE),
    trading_log = Stat(
description = 'Data Frame of trading log',
name = 'trading_log', 
in_report = FALSE,
general = FALSE),
    trading_log_ = Stat(
description = 'Full Data Frame of trading log',
name = 'trading_log_', 
in_report = FALSE,
general = TRUE))